[package]
name = "makeexpr"
version = "0.1.0"
authors = ["Gé Vissers <ge@q1t.nl>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arrayvec = "*"
num-rational = "*"
num-traits = "*"
fasthash = "*"
